ALTER TABLE repo_configs
  ADD COLUMN notify_pr_opened BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN notify_pr_merged BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN notify_pr_label BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN notify_comment BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN notify_issue_opened BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN notify_issue_closed BOOLEAN NOT NULL DEFAULT TRUE;
